name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.21"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Build ARM64
        run: GOOS=linux GOARCH=arm64 go build -o vitoagent_arm64 ./cmd/agent.go
      - name: Build AMD64
        run: GOOS=linux GOARCH=amd64 go build -o vitoagent_amd64 ./cmd/agent.go
